### ISSUE TITLE
is this thread safe?

### ISSUE THREAD

**Issue by saveriocastellano** [2ion/libqueue#5]
I'd like to know if a queue object is thread safe.. that is, if it can be operated by multiple threads..

**Comment by 2ion** [comment]
The opaque queue handle is given by
```
struct Queue {
	leveldb_t * db;
	leveldb_iterator_t* readItr;
	leveldb_iterator_t* writeItr;
	leveldb_readoptions_t* rop;
	leveldb_writeoptions_t* wop;
	leveldb_options_t* options;
	leveldb_comparator_t * cmp;
	char * error_strp;
};
```
Thread safety holds if all members are thread-safe. I haven't analyzed this now in detail (it wasn't designed to be explicitly thread-safe). Putting the complexities of LevelDB aside (see https://github.com/google/leveldb/blob/master/doc/index.md#concurrency and surrounding sections), per the current implementation, `error_strp` is not thread-safe due to how it's used e.g. in `queue_push()` if it's called by multiple threads without extra synchronisation.

So the answer is no.
